package api;

public class Solution {
    
    private static String TREAT1 =  "1R01                   .                       PENNSYLVANIA FISH & BOAT COMMISSION                                                   BUREAU OF ADMINISTRATION                                                                INQUIRY                                                                                                                    REG #: PA6628NN             PA TITLE #:              HULL ID: MEY025360976      MAKE: MEYERS BOAT COMPANY   MODEL:14 PRO             MODEL YR: 1976             PURCHASE DATE: 5/12/1997    REG ISSUE DATE:7/14/1997 REG EXP DATE: 3/31/2017    TYPE: 1 OPEN MOTORBOAT      ENG DRIVE: 1 OUTBOARD    HULL: 4 FIBERGLASS         USE: 1 PLEASURE             PROP: 1 PROPELLER        FUEL: 1 GAS                LENGTH: 14'                                                                          ** OWNER **                           ** CO-OWNER **                       WILLIAM RAMAKUS                                                                 607 WILSON AVE                                                                  RR 1                                                                            HARDING    PA 18643                                                             COUNTY: LUZERNE                         COUNTY:                                 DOB:                                    DOB:                                    DLN:                                    DLN:                                    PHONE #:                                PHONE #:                                                                                                                ALERTS/NOTES:   No alerts for 6628NN";
  
    private static String TREAT2 = "1R01                   .                       PENNSYLVANIA FISH &amp; BOAT COMMISSION                                                   BUREAU OF ADMINISTRATION                                                                INQUIRY                                                                                                                    REG #: PA5555CB             PA TITLE #: 0093264      HULL ID: KAW714941394      MAKE: KAWASAKI MOTORS   KA  MODEL:JET SKI            MODEL YR: 1994             PURCHASE DATE: 9/30/2003    REG ISSUE DATE:6/9/2010  REG EXP DATE: 3/31/2013    TYPE: 9 PERSONAL WATERCRAF  ENG DRIVE: 2 INBOARD     HULL: 4 FIBERGLASS         USE: 1 PLEASURE             PROP: 2 WATER JET        FUEL: 1 GAS                LENGTH: 10'                                                                          ** OWNER **                           ** CO-OWNER **                       AARON D SCHILLER                                                                1010 PARK DR                                                                    POTTSTOWN  PA 19464                                                             COUNTY: MONTGOMERY                      COUNTY:                                 DOB: 6/1/1980                           DOB:                                    DLN:                                    DLN:                                    PHONE #:                                PHONE #:                                                                                                                                                                                                ALERTS/NOTES:   No alerts for 5555CB";
    public static void main(String[] s) {
        if (TREAT1 != null && TREAT2 != null)
          System.out.println("");
        
        String str = String.format("Who is %2$S %1$s %3$.2f", "World", "Hello", 34f);
        System.out.println(TREAT1.substring(1224, 1230));
        System.out.println(TREAT2.substring(1145, 1151));
        System.out.println(TREAT1.indexOf("COUNTY"));
        System.out.println(TREAT2.indexOf("COUNTY"));
    }
}